@baseUrl = http://localhost:3333
# @authToken = {{authenticate.response.body.access_token}}

# @name create_subscription
POST {{baseUrl}}/subscriptions
Content-Type: application/json

{
  "name": "Rafael",
  "email": "rafael@example.com"
}

###

# @name referral_invite
GET {{baseUrl}}/invites/r123
