@baseUrl = http://localhost:3333
# @authToken = {{authenticate.response.body.access_token}}

# @name create_subscription
POST {{baseUrl}}/subscriptions
Content-Type: application/json

{
  "name": "Rafael",
  "email": "rafae1ll2@example.com",
  "referrer": "73ce9ba4-21a9-4466-9a6a-804d586990c9" 
}

###

# @name referral_invite
GET {{baseUrl}}/invites/73ce9ba4-21a9-4466-9a6a-804d586990c9


###

# @name ranking_clicks
GET {{baseUrl}}/subscribers/73ce9ba4-21a9-4466-9a6a-804d586990c9/ranking/clicks

###

# @name ranking_count
GET {{baseUrl}}/subscribers/73ce9ba4-21a9-4466-9a6a-804d586990c9/ranking/count

###